export { default as Home } from './Home'
export { default as Explore } from './Explore'
export { default as People } from './People'
export { default as Saved } from './Saved'
export {default as CreatePost} from './CreatePost'
export { default as NotFound } from './not-found'
export { default as PostDetails } from './PostDetails'
export {default as UpdatePost} from './UpdatePost'
export { default as ProfilePage } from './ProfilePage'